export const SPECIALTY_MAPPINGS: Record<string, string[]> = {
  cardiologia: [
    'cardiologia',
    'cardiologista',
    'cardio',
    'coração',
    'cardiovascular',
  ],
  ortopedia: ['ortopedia', 'ortopedista', 'ossos', 'fraturas', 'ortopédica'],
  ginecologia: ['ginecologia', 'ginecologista', 'gineco', 'mulher', 'feminina'],
  neurologia: ['neurologia', 'neurologista', 'neuro', 'cérebro', 'neurológica'],
  pediatria: ['pediatria', 'pediatra', 'criança', 'infantil', 'pediátrica'],
  dermatologia: ['dermatologia', 'dermatologista', 'pele', 'dermatológica'],
  psiquiatria: ['psiquiatria', 'psiquiatra', 'mental', 'psiquiátrica'],
  oftalmologia: [
    'oftalmologia',
    'oftalmologista',
    'olhos',
    'oftálmica',
    'visão',
  ],
  urologia: ['urologia', 'urologista', 'urológica', 'rim', 'bexiga'],
  endocrinologia: [
    'endocrinologia',
    'endocrinologista',
    'endócrino',
    'hormônios',
    'diabetes',
  ],
  gastroenterologia: [
    'gastroenterologia',
    'gastroenterologista',
    'gastro',
    'estômago',
    'digestivo',
  ],
  pneumologia: [
    'pneumologia',
    'pneumologista',
    'pulmão',
    'respiratório',
    'pulmonar',
  ],
  reumatologia: ['reumatologia', 'reumatologista', 'articulações', 'reumático'],
  oncologia: ['oncologia', 'oncologista', 'câncer', 'tumor', 'oncológica'],
  otorrinolaringologia: [
    'otorrinolaringologia',
    'otorrino',
    'ouvido',
    'nariz',
    'garganta',
  ],
};
